### ISSUE TITLE
inquire on svs English phnum label

### ISSUE THREAD

**Issue by li-henan** [spicytigermeat/SOFA_GUI#7]
Dear tigermeat,

TIGER is wonderful project,I use it in openutau.

Could I ask how you train the English svs model? I am a Graduate student,have trained chinese svs model before, and I researched training English svs model, my questions are about making english trainset,especially the phnum labeled.Do you use code in https://github.com/openvpi/MakeDiffSinger or improved the code？

I will appreciate it if you can reply .Look forward for further communication,thank you very much

**Comment by spicytigermeat** [comment]
Hi! The best advice I can offer you is to join the [DiffSinger discord server](https://discord.gg/zEwyXb3a5k), if you can. Many users in the server will be able to provide you with guidance! 

I will be closing this issue as it does not pertain to LabelMakr.
