### ISSUE TITLE
Many phonemes will stick together

### ISSUE THREAD

**Issue by ILG2021** [spicytigermeat/SOFA_GUI#8]
![image](https://github.com/spicytigermeat/LabelMakr/assets/93691919/81e3abfe-9b13-4aa2-94a2-c497bdaf8648)

**Comment by spicytigermeat** [comment]
This is a shortcoming of SOFA, as it's still in beta. All LabelMakr labels need to be manually corrected, as they're just a base to get you started. I'll be closing this issue as I'm aware it's a problem, but currently cannot do much to fix it.
